### ISSUE TITLE
getting illegal characters errors, conversion fails

### ISSUE THREAD

**Issue by wecul** [alexandermendes/marc2excel#3]
It is for sure a problem with my data, 
any hint on how i could get rid and past the following errors?
Perhaps a cleaning script, before the program's invocation?
thank you

Writing Excel data:  18%|████████████████████████████████▏                                                                                                                                              | 3084/16738 [01:41<07:27, 30.51rows/s]Traceback (most recent call last):
  File "/home/user/anaconda3/bin/marc2excel_cli.py", line 60, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/anaconda3/bin/marc2excel_cli.py", line 46, in main
    marc2excel(p, save_path, silent=silent, force_utf8=utf8)
  File "/home/user/anaconda3/lib/python3.6/site-packages/marc2excel/__init__.py", line 25, in marc2excel
    converter.marc2excel(path, out_path, force_utf8=force_utf8)
  File "/home/user/anaconda3/lib/python3.6/site-packages/marc2excel/main.py", line 81, in marc2excel
    self.sheets.write(out_path, data)
  File "/home/user/anaconda3/lib/python3.6/site-packages/marc2excel/sheets.py", line 30, in write
    ws.append(row)
  File "/home/user/anaconda3/lib/python3.6/site-packages/openpyxl/writer/write_only.py", line 234, in append
    self.writer.send(row)
  File "/home/user/anaconda3/lib/python3.6/site-packages/openpyxl/writer/write_only.py", line 164, in _write_header
    cell.value = value
  File "/home/user/anaconda3/lib/python3.6/site-packages/openpyxl/cell/cell.py", line 292, in value
    self._bind_value(value)
  File "/home/user/anaconda3/lib/python3.6/site-packages/openpyxl/cell/cell.py", line 191, in _bind_value
    value = self.check_string(value)
  File "/home/user/anaconda3/lib/python3.6/site-packages/openpyxl/cell/cell.py", line 156, in check_string
    raise IllegalCharacterError
openpyxl.utils.exceptions.IllegalCharacterError

**Comment by alexandermendes** [comment]
Just dropping this in here from the email you sent earlier as it's handy for future reference. I'll try to have a look a bit later!

[test.mrc.zip](https://github.com/alexandermendes/marc2excel/files/1085229/test.mrc.zip)

**Comment by wecul** [comment]
thank you very much

**Comment by alexandermendes** [comment]
Closing as this was nearly a year ago - can't remember if we resolved it but it can be reopened if not!
